### ISSUE TITLE
Support multibyte username on xml response.

### ISSUE THREAD

**Issue by ksauzz** [basho/riak_cs#628]
List users and show user API doesn't support multibyte on xml response. So name is garbled.
### create user

```
[vagrant@localhost ~]$ nkf --utf8 user.json
{"name": "ほげほげ", "email":"test@example.com"}
[vagrant@localhost ~]$ curl -i http://localhost:8080/riak-cs/user -H "Content-Type: application/json" -d @user.json
HTTP/1.1 201 Created
Vary: Accept
Server: Riak CS
Location: http://localhost:8080/riak-cs/user
Date: Mon, 29 Jul 2013 05:58:22 GMT
Content-Type: application/json
Content-Length: 263

{"email":"test@example.com","display_name":"test","name":"\u307b\u3052\u307b\u3052","key_id":"X9Z01FRHMO1YJWZT-1B7","key_secret":"ueFnnV1pwc1VNg_vHvnLKC6Ah1nw888rO90PnQ==","id":"6d0e53854eed0b7f3df6605aac08723855a89091bc84848f9346b0cfd39cd08b","status":"enabled"}[vagrant@localhost ~]$
```
#### XML response

```
[vagrant@localhost ~]$ ./s3curl.pl --id admin -- -x localhost:8080 http://riak-cs.s3.amazonaws.com/users

--OP3SKSJCRRKG6UJN3NZ50NKLFIJ47Y3
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?><Users><User><Email>test@example.com</Email><DisplayName>test</DisplayName><Name>ã»ãã»ã</Name><KeyId>X9Z01FRHMO1YJWZT-1B7</KeyId><KeySecret>ueFnnV1pwc1VNg_vHvnLKC6Ah1nw888rO90PnQ==</KeySecret><Id>6d0e53854eed0b7f3df6605aac08723855a89091bc84848f9346b0cfd39cd08b</Id><Status>enabled</Status></User></Users>
--OP3SKSJCRRKG6UJN3NZ50NKLFIJ47Y3
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?><Users><User><Email>user@example.com</Email><DisplayName>user</DisplayName><Name>user</Name><KeyId>O0YC0RKWM69HIG0NDVG1</KeyId><KeySecret>QdHYZVitFaGqfh-LSriGcMU_NDYNAh9z2MHhXg==</KeySecret><Id>02e40edb2ad4049bb75c2d4963f720a640f9e1f716c721f326759473afbda80d</Id><Status>enabled</Status></User></Users>
--OP3SKSJCRRKG6UJN3NZ50NKLFIJ47Y3
```
#### JSON response

```
[vagrant@localhost ~]$ ./s3curl.pl --id admin -- -x localhost:8080 -H "Accept:application/json" http://riak-cs.s3.amazonaws.com/users

--LHDGOZNBC03AS9SJORMHHDS4WMEPTT9
Content-Type: application/json

[{"email":"test@example.com","display_name":"test","name":"\u307b\u3052\u307b\u3052","key_id":"X9Z01FRHMO1YJWZT-1B7","key_secret":"ueFnnV1pwc1VNg_vHvnLKC6Ah1nw888rO90PnQ==","id":"6d0e53854eed0b7f3df6605aac08723855a89091bc84848f9346b0cfd39cd08b","status":"enabled"}]
--LHDGOZNBC03AS9SJORMHHDS4WMEPTT9
Content-Type: application/json

[{"email":"user@example.com","display_name":"user","name":"user","key_id":"O0YC0RKWM69HIG0NDVG1","key_secret":"QdHYZVitFaGqfh-LSriGcMU_NDYNAh9z2MHhXg==","id":"02e40edb2ad4049bb75c2d4963f720a640f9e1f716c721f326759473afbda80d","status":"enabled"}]
```
#### XML response.

```
[vagrant@localhost ~]$ ./s3curl.pl --id admin -- -x localhost:8080 http://riak-cs.s3.amazonaws.com/user/X9Z01FRHMO1YJWZT-1B7/
<?xml version="1.0" encoding="UTF-8"?><User><Email>test@example.com</Email><DisplayName>test</DisplayName><Name>ã»ãã»ã</Name><KeyId>X9Z01FRHMO1YJWZT-1B7</KeyId><KeySecret>ueFnnV1pwc1VNg_vHvnLKC6Ah1nw888rO90PnQ==</KeySecret><Id>6d0e53854eed0b7f3df6605aac08723855a89091bc84848f9346b0cfd39cd08b</Id><Status>enabled</Status></User>
```
#### JSON response

```
[vagrant@localhost ~]$ ./s3curl.pl --id admin -- -x localhost:8080 -H "Accept:application/json" http://riak-cs.s3.amazonaws.com/user/X9Z01FRHMO1YJWZT-1B7/
{"email":"test@example.com","display_name":"test","name":"\u307b\u3052\u307b\u3052","key_id":"X9Z01FRHMO1YJWZT-1B7","key_secret":"ueFnnV1pwc1VNg_vHvnLKC6Ah1nw888rO90PnQ==","id":"6d0e53854eed0b7f3df6605aac08723855a89091bc84848f9346b0cfd39cd08b","status":"enabled"}[vagrant@localhost ~]$
```

**Comment by reiddraper** [comment]
Is this a 1.4 blocker?

**Comment by ksauzz** [comment]
No. Thank you for the attention.

**Comment by shino** [comment]
Good reference for Latin-1 and Unicode in Erlang.
Codepoints, encodings, string literals, binaries and more.
http://www.erlang-factory.com/conference/ErlangUserConference2013/speakers/PatrikNyblom

**Comment by reiddraper** [comment]
Thoughts on priorities of this for 1.5? Scope of work?

**Comment by kuenishi** [comment]
It's not a bit feature so I think we can do it.

**Comment by kuenishi** [comment]
I think it's too much to support unicode. But the bad situation is, users can _create_ a user named with unicode. So adding a validation that accepts only ascii printable characters would be enough. Any thoughts? CC: @shino

**Comment by kuenishi** [comment]
As there are no customer request for now, I'll suggest above change to Riak CS and decision not to support unicode chars as user names.

**Comment by shino** [comment]
> I'll suggest above change to Riak CS and decision not to support unicode chars as user names.

+1

**Comment by kuenishi** [comment]
Will be solved after #787 fixed.

**Comment by shino** [comment]
Addressed by #794

**Comment by reiddraper** [comment]
Previous comments suggested we _would_ not_ support unicode usernames, but #794 seems to add support them. Is that correct? Are there any issues with names that might have been saved with previous versions of Riak CS?

**Comment by kuenishi** [comment]
I assume that any previous version of Riak CS cannot print multibyte usernames correctly and thus no one is using unicode characters.
My aim was to reduce complexity and further fix, but Shino's fix on #794 has unexpected side effect, which is good. We still won't recommend unicode names, but it works so far.

**Comment by shino** [comment]
Fixed by #807.
Non-ASCII UTF-8 characters can be used and printed properly.
